apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpletimeservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpletimeservice
  template:
    metadata:
      labels:
        app: simpletimeservice
    spec:
      containers:
        - name: simpletimeservice
          image: shrutihosagoudar/simpletimeservice:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: simpletimeservice-service
spec:
  selector:
    app: simpletimeservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
